config/routes.rb
Rails.application.routes.draw do

  root 'users/homes#about'
  devise_for :admins, path: 'auth', path_names: { sign_in: 'panda_and_coffee_with_ryoko_play_login', sign_out: 'panda_and_coffee_with_ryoko_play_logout', password: 'panda_and_coffee_with_ryoko_play_secret', confirmation: 'panda_and_coffee_with_ryoko_play_verification', unlock: 'panda_and_coffee_with_ryoko_play_unblock', registration: 'panda_and_coffee_with_ryoko_play_register', sign_up: 'panda_and_coffee_with_ryoko_play_cmon_let_me_in' }, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations',
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
  }

  namespace :admins do
  	resources :users, only: [:index, :show]
    put 'users/:id/hide' => 'users#hide', as: 'users_hide'

    resources :gives, only: [:index, :show]
    put 'gives/:id/hide' => 'gives#hide', as: 'gives_hide'

    resources :gifts, only: [:index, :show]
    put 'gifts/:id/hide' => 'gifts#hide', as: 'gifts_hide'

    resources :posts, only: [:index, :show]
    put 'posts/:id/hide' => 'posts#hide', as: 'posts_hide'

    resources :tags, only: [:index, :create]
    put 'tags/:id/hide' => 'tags#hide', as: 'tags_hide'
  end

  namespace :users do
    get 'homes/about' => 'homes#about'
    get ':id/unsubscribe' => "homes#unsubscribe", as: "unsubscribe"
    get 'search' => 'homes#search'

    resources :users, only: [:show, :edit, :update]
    put 'users/:id/hide' => 'users#hide', as: 'users_hide'
    get '/users/:id' => 'users#favorites', as: 'favorites'

    resources :rooms, only: [:show, :create]
    put 'rooms/:id/hide' => 'rooms#hide', as: 'rooms_hide'

    resources :gives, only: [:index, :show, :new, :create, :edit, :update] do
    	resources :give_comments, only: [:create]
    end

    resources :gifts, only: [:index, :show, :new, :create, :edit, :update] do
      resources :gift_comments, only: [:create, :destroy]
    end
    put 'gives/:id/hide' => 'gives#hide', as: 'gives_hide'
    put 'give_comments/:id/hide' => 'give_comments#hide', as: 'give_comments_hide'

    put 'gifts/:id/hide' => 'gifts#hide', as: 'gifts_hide'

    resources :posts, only: [:index, :show, :new, :create, :edit, :update] do
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    put 'posts/:id/hide' => 'posts#hide', as: 'posts_hide'

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/give.rb
class Give < ApplicationRecord
  has_many :item_images
  has_many :give_comments, dependent: :destroy

  belongs_to :user

  accepts_attachments_for :item_images, attachment: :item_image

  enum status:{Yet:0,Done:1}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def active_for_authentication?
    super && (self.is_deleted == nil)
  end

  has_many :rooms, dependent: :destroy
  has_many :gifts, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :gift_comments
  has_many :post_comments

  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  attachment :user_image

  def already_favorited?(post)
    self.favorites.exists?(post_id: post.id)
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/favorites_controller.rb
class Users::FavoritesController < ApplicationController

	before_action :set_variables
  def create
  	favorite = current_user.favorites.new(post_id: @post.id)
    favorite.save
  end

  def destroy
  	favorite = current_user.favorites.find_by(post_id: @post.id)
    favorite.destroy
  end

  private
  def set_variables
    @post = Post.find(params[:post_id])
    @id_name = "#favorite-link-#{@post.id}"
  end
end

app/controllers/users/gift_comments_controller.rb
class Users::GiftCommentsController < ApplicationController

	before_action :authenticate_user!, only: [:create, :destroy ]

	def create
      @comment = current_user.gift_comments.build(comment_params)
      @comment.user = current_user
      @comment.save!
      @gift = Gift.find(params[:gift_id])
      @comments = @gift.gift_comments.where(is_deleted: nil).order(created_at: :desc)
      render 'create.js.erb'
    end

    def destroy
      @comment = GiftComment.find(params[:id])
      if @comment.user == current_user
          @comment.destroy
      end
    end

    private

	  def comment_params
	    params.require(:gift_comment)
	          .permit(:comment)
	          .merge(gift_id: params[:gift_id])
	  end
end

app/controllers/users/gifts_controller.rb
class Users::GiftsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :update, :hide ]

  def new
  	@gift = Gift.new
  end

  def create
    @gift = Gift.new(gift_params)
    @gift.user = current_user
    @gift.save
    redirect_to users_gifts_path
  end

  def update
    @gift = Gift.find(params[:id])
    if @gift.user == current_user
        @gift.update(gift_params)
    end
    redirect_to users_gift_path
  end

  def index
  	gift = params[:q]
    @search = Gift.ransack(gift)
    @users = User.where(is_deleted: nil)
    x = []
    @users.each do |user|
      x << user.id
    end
    @result = @search.result(distinct: true).page(params[:page]).where(is_deleted: nil).where(user_id: x).per(10).order(created_at: :desc)
    # @gifts = Gift.all.order(created_at: :desc)
    @gift = Gift.new
  end

  def show
    @gift = Gift.find(params[:id])
    @comment = GiftComment.new
    @users = User.where(is_deleted: nil)
    x = []
    @users.each do |user|
      x << user.id
    end
    @comments = @gift.gift_comments.where(is_deleted: nil).where(user_id: x).order(created_at: :desc)
  end

  def hide
    @gift = Gift.find(params[:id])
    if @gift.user == current_user
        @gift.update(is_deleted: true)
    end
    redirect_to users_gifts_path
  end

  private
  def gift_params
  	params.require(:gift).permit(:user_id, :item_name, :title, :body, :status, :is_deleted, item_images_item_images: [])
  end
end

app/controllers/users/give_comments_controller.rb
class Users::GiveCommentsController < ApplicationController

	before_action :set_comment, only: [:destroy]

	def create
      @comment = current_user.give_comments.build(comment_params)
      @comment.save!
      @give = Give.find(params[:give_id])
      @comments = @give.give_comments.order(created_at: :desc)
      render 'create.js.erb'
    end

    def hide
      @comment = Comment.find(params[:id])
      @give.update(is_deleted: true)
    end

    private
	  def set_comment
	    @comment = Comment.find_by(id: params[:id])
	  end

	  def comment_params
	    params.require(:give_comment)
	          .permit(:comment)
	          .merge(give_id: params[:give_id])
	  end
end

app/controllers/users/gives_controller.rb
class Users::GivesController < ApplicationController

  def new
  	@give = Give.new
  end

  def create
    @give = Give.new(give_params)
    @give.user = current_user
    @give.save
    redirect_to users_gives_path
  end

  def update
    @give = Give.find(params[:id])
    @give.user = current_user
    @give.update(give_params)
    redirect_to users_gife_path
  end

  def index
    @gives = Give.all.order(created_at: :desc)
    @give = Give.new
  end

  def show
    @give = Give.find(params[:id])
    @comment = GiveComment.new
    @comments = @give.give_comments.order(created_at: :desc)
  end

  def hide
    @give = Give.find(params[:id])
    @give.update(is_deleted: true)
    redirect_to users_gives_path
  end

  private
  def give_params
  	params.require(:give).permit(:user_id, :item_name, :title, :body, :status, :is_deleted, item_images_item_images: [])
  end
end

app/controllers/users/homes_controller.rb
class Users::HomesController < ApplicationController
  def about
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/post_comments_controller.rb
class Users::PostCommentsController < ApplicationController

	before_action :authenticate_user!, only: [:create, :destroy ]

	def create
      @comment = current_user.post_comments.build(comment_params)
      @comment.user = current_user
      @comment.save!
      @post = Post.find(params[:post_id])
      @comments = @post.post_comments.where(is_deleted: nil).order(created_at: :desc)
      render 'create.js.erb'
    end

    def destroy
      @comment = PostComment.find(params[:id])
      if @comment.user == current_user
          @comment.destroy
      end
    end

    private
	  def comment_params
	    params.require(:post_comment)
	          .permit(:comment)
	          .merge(post_id: params[:post_id])
	  end
end

app/controllers/users/posts_controller.rb
class Users::PostsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :update, :hide ]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.save
    redirect_to users_posts_path
  end

  def update
    @post = Post.find(params[:id])
    if @post.user == current_user
        @post.update(post_params)
    end
    redirect_to users_post_path
  end

  def index
    post = params[:q]
    @search = Post.ransack(post)
    @users = User.where(is_deleted: nil)
    x = []
    @users.each do |user|
      x << user.id
    end
    @result = @search.result(distinct: true).page(params[:page]).where(is_deleted: nil).where(user_id: x).per(10).order(created_at: :desc)
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @comment = PostComment.new
    @users = User.where(is_deleted: nil)
    x = []
    @users.each do |user|
      x << user.id
    end
    @comments = @post.post_comments.where(is_deleted: nil).where(user_id: x).order(created_at: :desc)
  end

  def hide
    @post = Post.find(params[:id])
    if @post.user == current_user
        @post.update(is_deleted: true)
    end
    redirect_to users_posts_path
  end

  private
  def post_params
  	params.require(:post).permit(:user_id, :title, :body, :post_image, :is_deleted)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/rooms_controller.rb
class Users::RoomsController < ApplicationController

  before_action :authenticate_user!, only: [:create, :hide ]

	def index
    #チャット相手の名前で一覧表示するにはcurrent_user.rooms.allだと、room.name("DM")で表示させることになり、誰とのトークか見分けつかない。
    #entryは塊になって浮いてる状態なので、配列にするには、entryを一件ずつ取り出して、配列の箱に入れる。
    @currentEntries = current_user.entries
    myRoomIds = [] #配列が入る箱を作る
    @currentEntries.each do |entry| #カレントユーザーのentry 1件ずつだす
      myRoomIds << entry.room.id # << は、右辺のentry.room.idを左辺のmyRoomIdsの中に入れる
    end
    @anotherEntries = Entry.where(room_id: myRoomIds).where.not(user_id: current_user.id).where(is_deleted: nil).order(created_at: :desc) #where~~かつwhere.not~~~~ という意味
  end
  def show
  	@room = Room.find(params[:id])
    @room.users.each do |user|
      if user.is_deleted != nil
        redirect_to users_user_path(current_user)
      end
    end
  	if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
  	  @messages = @room.messages
  	  @entries = @room.entries
  	else
  	  redirect_back(fallback_location: root_path)
    end
  end
  def create
    @room = Room.create(name: "DM")
    @entry1 = Entry.create(room_id:@room.id, user_id:current_user.id)
    @entry2 = Entry.create(params.require(:room).permit(:user_id).merge(:room_id => @room.id))
    redirect_to users_room_path(@room.id)
  end
  def hide
    @room = Room.find(params[:id])
    @room.update(is_deleted: true)
    redirect_to users_user_path(current_user)
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_user, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def reject_user
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user
      if (@user.valid_password?(params[:user][:password]) && (@user.active_for_authentication? == false))
        flash[:error] = "Unsubscribed"
        redirect_to new_user_session_path
      end
    else
      flash[:error] = "Enter the required information."
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/gives_helper.rb
module Admins::GivesHelper
end

app/views/users/gives/index.html.erb
<section class="container clearfix">

<div class="index_content">
  <h2 class="index_content_text">Gives</h2>
  <a class="js-modal-open btn btn-dark ml-3 mb-3" href="">New give</a>
</div>
  <div class="modal js-modal">
    <div class="modal__bg js-modal-close"></div>
      <div class="modal__content">
        <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">New give</h5>
        <a class="js-modal-close btn btn-dark" href="">×</a>
      </div>
        <%= form_for @give,url:users_gives_path, remote: true do |f| %>
          <%= f.label :item_name %><br>
          <%= f.text_field :item_name, class:"form-control", placeholder: "item_name" %><br>
          <%= f.label :Title %><br>
          <%= f.text_field :title, class:"form-control", placeholder: "title" %><br>
          <%= f.label :本文 %><br>
          <%= f.text_area :body, class:"form-control", placeholder: "本文" %><br>
          <p>image</p>
          <%= f.attachment_field :item_images_item_images, multiple: true %><br>
          <%= f.hidden_field :status, :value => "Yet" %>
          <%= f.submit "create", class:"btn btn-dark mt-3" %>
        <% end %>
      </div>
    </div>
  </div>

    <table  class="table table-hover table-inverse">
      <thead = class="thead thead-dark">
        <tr>
          <th>user</th>
          <th>image</th>
          <th>item_name</th>
          <th>Title</th>
          <th>status</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @gives.each do |give| %>
        <tr>
          <td>
            <%= link_to users_user_path(give.user) do %>
              <%= attachment_image_tag give.user, :user_image, format: 'jpeg', size: '60x60', class: "pull-left profile-img rounded-circle", fallback: "no_image.jpg" %><br><span class="text-dark"><%= give.user.name %></span>
            <% end %>
          </td>
          <td>
              <%= attachment_image_tag give.item_images.first, :item_image, size: '100x100', format: 'jpeg' %>
          </td>
          <td><span><%= truncate(give.item_name, length: 8) %></span></td>
          <td><span><%= truncate(give.title, length: 8) %></span></td>
          <td><%= give.status %></td>
          <td><span><%= give.created_at.strftime("%Y-%m-%d %H:%M") %></span></td>
          <td><%= link_to "show", users_gife_path(give), class: "btn btn-dark" %></td>
          </div>
        </tr>
        <% end %>
      </tbody>
    </table>
</section>

app/views/users/gives/show.html.erb
<section class="container clearfix">
  <h2>Give show</h2>
  <p class="trim-image-to-circle">
	<%= attachment_image_tag @give.user, :user_image, format: 'jpeg', size: '60x60', class: "pull-left profile-img rounded-circle mt-3", fallback: "no_image.jpg" %>
  </p>
  <%= @give.user.name %>
  <%= @give.item_name %>
  <%= @give.created_at.strftime("%Y-%m-%d %H:%M") %>
  <%= @give.title %>
  <% @give.item_images.each do |item_image| %>
    <%= attachment_image_tag item_image, :item_image, size: '150x150', format: 'jpeg' %>
  <% end %>
  <%= @give.body %>
  <% if @give.user == current_user %>
	<div class="index_content">
	  <a class="js-modal-open btn btn-dark mb-3" href="">Edit give</a>
	</div>
	  <div class="modal js-modal">
	    <div class="modal__bg js-modal-close"></div>
	      <div class="modal__content">
	        <div class="modal-header">
	        <h5 class="modal-title" id="staticBackdropLabel">Edit give</h5>
	        <a class="js-modal-close btn btn-dark" href="">×</a>
	      </div>
	        <%= form_for @give,url:users_gife_path, method: :put, remote: true do |f| %>
	          <%= f.label :item_name %><br>
	          <%= f.text_field :item_name, class:"form-control", placeholder: "item_name" %><br>
	          <%= f.label :Title %><br>
	          <%= f.text_field :title, class:"form-control", placeholder: "title" %><br>
	          <%= f.label :本文 %><br>
	          <%= f.text_area :body, class:"form-control", placeholder: "本文" %><br>
	          <p>image</p>
	          <%= f.attachment_field :item_images_item_images, multiple: true %><br>
	          <%= f.label :status, class: "mt-3" %><br>
	          <p>
	            <%= f.radio_button :status, :Yet %> Yet
	            <%= f.radio_button :status, :Done, class: "ml-5" %> Done
	          </p>
	          <%= f.submit "update", class:"btn btn-dark" %>
	        <% end %>
	      </div>
	    </div>
	  </div>
    <%= link_to "destroy", users_gives_hide_path, class:"btn btn-dark mb-3" %>
  <% else %>
  <% end %>

<p>
  <a class="btn btn-dark" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
    Comments
  </a>
</p>
<div class="collapse" id="collapseExample">
  <div class="card card-body">

<div class="container pt-5">
  <div class="row mb-3">
    <div class="col-lg-8 offset-lg-2">
      <%= form_for @comment,url: users_gife_give_comments_path(@give.id), method: :post, remote: true do |f| %>
        <%= f.label :comment, t('.comment')%>
      <% if user_signed_in? %>
        <%= f.text_area :comment, class: "form-control mb-3", placeholder: "comment" , rows: "4" %>
        <%= f.submit "create", class: "btn btn-dark" %>
      <% end %>
      <% end %>
    </div>
  </div>
  <%= render 'users/give_comments/comments_area', comments: @comments %>
</div>
</div>
</div>

</section>